### ISSUE TITLE
how do you background color of graph?

### ISSUE THREAD

**Issue by jlgerber** [DomParfitt/graphviz-react#12]
is it possible through css?

**Comment by magjac** [comment]
You can use the Graphviz [bgcolor](https://www.graphviz.org/doc/info/attrs.html#d:bgcolor) attribute in your DOT source, but of course you could use the CSS [background](https://www.w3schools.com/cssref/css3_pr_background.asp) property as well.

**Comment by DomParfitt** [comment]
As @magjac said you can use the attributes in the actual DOT graph string. For example the following would give a single node coloured red:
```
graph { 
  a[fillcolor=red style=filled]
}
```
If you want to use CSS it's just a case of applying the correct styling to the correct SVG element. The entire graph is rendered inside an SVG `polygon` element. So, you could include the following to colour the entire background red:
```css
polygon {
    fill: red;
}
```
The actual graph nodes are rendered as `ellipse`s, so you can override the background colour for nodes using that, or by applying the DOT attributes as above.

Hope that helps. Let me know if you need any further help although I'm by no means a CSS expert.

**Comment by jlgerber** [comment]
Thank you! Is there a way of affecting the edge colors via css as well?

**Comment by DomParfitt** [comment]
Yes, the edges are rendered as SVG `path` elements, so you can set the line colour in CSS using the `stroke` property, like so:
```css
path {
  stroke: red;
}
```

It's worth noting that if you're using a digraph this won't fill the pointers on the edges. The pointers are SVG `polygon` elements so obviously if you try to set these whilst also setting the background colour using CSS you'll get a clash. It's probably worth using the classes of the elements to do the selection. Everything is wrapped in an SVG `g` element, which has a class (`graph`, `node` or `edge`). So to select all edges and colour them you could do:
```css
.edge>path {
  stroke: red;
}

.edge>polygon {
  stroke: red;
  fill: red;
}
```

Hope that helps.
