### ISSUE TITLE
Thanks! - I ported this to Angular

### ISSUE THREAD

**Issue by SamuelMarks** [DomParfitt/graphviz-react#13]
Really was helpful!

Here's the code:
https://github.com/glaucoma/glaucoma-risk-calculator-analytics-web-frontend/commit/88569b2bf1fd439dcb7de3b84ef6a2a7c1e642af#diff-8

If you—or anyone—cares I can put it into its own repository and upload it to npmjs.

PS: Also on the license side how do you want me to attribute this to you? - Docstring at top of file?

**Comment by DomParfitt** [comment]
Glad you liked it!

If you feel your port could be of use to others then by all means make it into its own package.

As far as attribution goes I'm not too fussed really, if you want to put a note saying "inspired by/ported from" then that's fine.
