### ISSUE TITLE
HTML-like Labels support?

### ISSUE THREAD

**Issue by un0btanium** [DomParfitt/graphviz-react#35]
Does this allow nodes to be defined with HTML-like labels? I dont seem to get it to work in the demo. For example:

```javascript
graph { 
a [label=<<b>Test</b>>]
}
```

it throws  `Parse Error: Cannot read property '3' of null`.

**Comment by DomParfitt** [comment]
Hi @un0btanium,

I think this is only an issue with the demo, which uses [graphlib-dot](https://github.com/dagrejs/graphlib-dot) to validate that the input string is valid DOT (the code for that is [here](https://github.com/DomParfitt/graphviz-react/blob/master/demo/src/components/GraphInput/GraphInput.tsx#L33-L39)) and it seems as if it doesn't correctly parse HTML-like labels. This code isn't present in the actual `graphlib-react` library, which does no validation on the structure of the input strings and leaves that up to the consumer of the library, it only affects the demo.

A quick look at the `graphlib-dot` repo and [this issue](https://github.com/dagrejs/graphlib-dot/issues/27) seems to be related to the issue you're having. Setting the `labelType` to `"html"`, as per the below example, should allow you to use HTML-like labels in the demo.

```dot
graph { 
  a [label=<<b>Test</b>> labelType="html"]
}
```

Hope that helps.

**Comment by DomParfitt** [comment]
Actually, using `labelType` doesn't seem to solve the issue. Regardless, it's only an issue with the demo and not the actual library.

**Comment by un0btanium** [comment]
Oh, I see. That's good news. I tried it out and it does indeed work properly in my React application.
